### ISSUE TITLE
If selecting first or last image 'Done' buttons stops working

### ISSUE THREAD

**Issue by developer82** [Bouncingfish/TiMediaPicker#2]
On the emulator I have 5 example images.
If I open the gallery and in my selection include either the first or last image then the Done button doesn't work anymore - even if unselecting those images.
Going back and entering album again also doesn't help - you have to close the gallery and reopen it altogether to make it work again.

**Comment by bduyng** [comment]
hi @developer82 . thanks for your report.  It would be great if you can check 1.0.2 version and close the issue. You can also check new [demo](https://github.com/Bouncingfish/TiMediaPicker/blob/master/example.gif) I just added in README to see how the module works.

**Comment by jonasfunk** [comment]
I'm also experiencing this issue using 1.0.2

**Comment by jonasfunk** [comment]
Hi Jason, is this issue fixed now?

**Comment by jonasfunk** [comment]
Hi Jason, was this issue fixed, since it was closed?
